import AppKit
import BlurtEngine
import CryptoKit
import Foundation

@MainActor
enum ClipboardSyncPasteboard {
  static let marker = NSPasteboard.PasteboardType("com.vibedictate.clipboard-sync")
  static let excluded = Set([
    "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType", "com.vibedictate.dictation-record-id",
  ])
  static let allowed = ClipboardSyncLimits.allowedTypes
  private static let imageTypes = ["public.png", "public.jpeg", "public.tiff"]

  struct Snapshot: Sendable {
    let items: [ClipboardSyncItem]
    let files: [URL]
    let fingerprint: Data
    let changeCount: Int
  }

  static func snapshot(pasteboard: NSPasteboard = .general) throws -> Snapshot? {
    let count = pasteboard.changeCount
    guard let entries = pasteboard.pasteboardItems, !entries.isEmpty else { return nil }
    guard entries.count <= ClipboardSyncLimits.maximumItems else { throw ClipboardSyncFiles.FileError.limit }
    guard
      !entries.contains(where: { item in
        item.types.contains { excluded.contains($0.rawValue) || $0 == marker }
      })
    else { return nil }
    var items: [ClipboardSyncItem] = []
    var files: [URL] = []
    var total = 0
    for entry in entries {
      if let path = entry.string(forType: .fileURL), let url = URL(string: path), url.isFileURL {
        files.append(url)
        continue
      }
      let representations = try representations(entry, total: &total)
      if !representations.isEmpty { items.append(ClipboardSyncItem(representations: representations)) }
    }
    if !files.isEmpty { items = [] }
    guard pasteboard.changeCount == count, !items.isEmpty || !files.isEmpty else { return nil }
    return Snapshot(
      items: items, files: files, fingerprint: fingerprint(items: items, files: files), changeCount: count)
  }

  private static func fingerprint(items: [ClipboardSyncItem], files: [URL]) -> Data {
    var hash = SHA256()
    hash.update(data: Data("items:\(items.count):".utf8))
    for item in items {
      hash.update(data: Data("representations:\(item.representations.count):".utf8))
      for type in item.representations.keys.sorted() {
        hash.update(data: Data("type:\(type.utf8.count):".utf8))
        hash.update(data: Data(type.utf8))
        if let data = item.representations[type] {
          hash.update(data: Data("bytes:\(data.count):".utf8))
          hash.update(data: data)
        }
      }
    }
    hash.update(data: Data("files:\(files.count):".utf8))
    for file in files {
      let path = file.absoluteString
      hash.update(data: Data("path:\(path.utf8.count):".utf8))
      hash.update(data: Data(path.utf8))
    }
    return Data(hash.finalize())
  }

  static func contentFingerprint(_ snapshot: ClipboardSyncPasteboard.Snapshot, files: [ClipboardSyncFile]) -> Data {
    guard !files.isEmpty else { return snapshot.fingerprint }
    var hash = SHA256()
    hash.update(data: snapshot.fingerprint)
    for file in files {
      hash.update(data: Data("bytes:\(file.data.count):".utf8))
      hash.update(data: file.data)
    }
    return Data(hash.finalize())
  }

  private static func representations(_ entry: NSPasteboardItem, total: inout Int) throws -> [String: Data] {
    var representations: [String: Data] = [:]
    for type in entry.types where allowed.contains(type.rawValue) && !imageTypes.contains(type.rawValue) {
      if let data = entry.data(forType: type) {
        total += data.count
        guard total <= ClipboardSyncFiles.maximumBytes else { throw ClipboardSyncFiles.FileError.limit }
        representations[type.rawValue] = data
      }
    }
    if let image = preferredImage(entry) {
      total += image.data.count
      guard total <= ClipboardSyncFiles.maximumBytes else { throw ClipboardSyncFiles.FileError.limit }
      representations[image.type] = image.data
    }
    return representations
  }

  /// Image aliases often include a huge uncompressed TIFF beside compact PNG.
  /// Materialize one readable representation in preference order, then stop.
  private static func preferredImage(_ entry: NSPasteboardItem) -> (type: String, data: Data)? {
    for raw in imageTypes {
      let type = NSPasteboard.PasteboardType(raw)
      if entry.types.contains(type), let data = entry.data(forType: type), !data.isEmpty {
        return (raw, data)
      }
    }
    return nil
  }

  static func apply(
    _ payload: ClipboardSyncPayload, urls: [URL], pasteboard: NSPasteboard = .general, expectedChangeCount: Int? = nil
  ) -> Bool {
    var objects: [NSPasteboardWriting] = []
    for item in payload.items {
      let entry = NSPasteboardItem()
      for (type, data) in item.representations where allowed.contains(type) {
        entry.setData(data, forType: NSPasteboard.PasteboardType(type))
      }
      entry.setString(payload.id.uuidString, forType: marker)
      objects.append(entry)
    }
    for url in urls {
      let entry = NSPasteboardItem()
      entry.setString(url.absoluteString, forType: .fileURL)
      entry.setString(payload.id.uuidString, forType: marker)
      objects.append(entry)
    }
    guard !objects.isEmpty else { return false }
    if let expectedChangeCount, pasteboard.changeCount != expectedChangeCount { return false }
    pasteboard.clearContents()
    return pasteboard.writeObjects(objects)
  }

  static var isTemporary: Bool {
    NSPasteboard.general.types?.contains { excluded.contains($0.rawValue) } ?? false
  }
}
